// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hello.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Passwd               string   `protobuf:"bytes,2,opt,name=Passwd,proto3" json:"Passwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserReq) Reset()         { *m = UserReq{} }
func (m *UserReq) String() string { return proto.CompactTextString(m) }
func (*UserReq) ProtoMessage()    {}
func (*UserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{0}
}

func (m *UserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserReq.Unmarshal(m, b)
}
func (m *UserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserReq.Marshal(b, m, deterministic)
}
func (m *UserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserReq.Merge(m, src)
}
func (m *UserReq) XXX_Size() int {
	return xxx_messageInfo_UserReq.Size(m)
}
func (m *UserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserReq proto.InternalMessageInfo

func (m *UserReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserReq) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

type UserResp struct {
	ErrorCode            uint32    `protobuf:"varint,1,opt,name=ErrorCode,proto3" json:"ErrorCode,omitempty"`
	Message              string    `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Info                 *UserInfo `protobuf:"bytes,3,opt,name=Info,proto3" json:"Info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UserResp) Reset()         { *m = UserResp{} }
func (m *UserResp) String() string { return proto.CompactTextString(m) }
func (*UserResp) ProtoMessage()    {}
func (*UserResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{1}
}

func (m *UserResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResp.Unmarshal(m, b)
}
func (m *UserResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResp.Marshal(b, m, deterministic)
}
func (m *UserResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResp.Merge(m, src)
}
func (m *UserResp) XXX_Size() int {
	return xxx_messageInfo_UserResp.Size(m)
}
func (m *UserResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResp.DiscardUnknown(m)
}

var xxx_messageInfo_UserResp proto.InternalMessageInfo

func (m *UserResp) GetErrorCode() uint32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *UserResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UserResp) GetInfo() *UserInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type UserInfo struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=Token,proto3" json:"Token,omitempty"`
	Age                  uint32   `protobuf:"varint,4,opt,name=Age,proto3" json:"Age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{2}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *UserInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserInfo) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *UserInfo) GetAge() uint32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func init() {
	proto.RegisterType((*UserReq)(nil), "proto.UserReq")
	proto.RegisterType((*UserResp)(nil), "proto.UserResp")
	proto.RegisterType((*UserInfo)(nil), "proto.UserInfo")
}

func init() { proto.RegisterFile("hello.proto", fileDescriptor_61ef911816e0a8ce) }

var fileDescriptor_61ef911816e0a8ce = []byte{
	// 242 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8e, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x4d, 0x9a, 0xb6, 0x66, 0x82, 0xad, 0x0c, 0x22, 0x8b, 0x78, 0x28, 0xf1, 0xd2, 0x53,
	0x0e, 0x15, 0x8f, 0x1e, 0x8a, 0xf5, 0x10, 0x50, 0x91, 0x45, 0xbd, 0xc7, 0x76, 0x5c, 0xc5, 0xba,
	0x93, 0xee, 0x56, 0xfc, 0xfb, 0xb2, 0xb3, 0x55, 0xe3, 0x69, 0xe7, 0x7b, 0xcb, 0xbc, 0xf9, 0xa0,
	0x78, 0xa5, 0xf5, 0x9a, 0xab, 0xd6, 0xf1, 0x96, 0xb1, 0x2f, 0x4f, 0x79, 0x01, 0xc3, 0x47, 0x4f,
	0x4e, 0xd3, 0x06, 0x11, 0xb2, 0xbb, 0xe6, 0x83, 0x54, 0x32, 0x49, 0xa6, 0xb9, 0x96, 0x19, 0x8f,
	0x61, 0x70, 0xdf, 0x78, 0xff, 0xb5, 0x52, 0xa9, 0xa4, 0x3b, 0x2a, 0x0d, 0xec, 0xc7, 0x35, 0xdf,
	0xe2, 0x29, 0xe4, 0xd7, 0xce, 0xb1, 0xbb, 0xe2, 0x55, 0x5c, 0x3e, 0xd0, 0x7f, 0x01, 0x2a, 0x18,
	0xde, 0x92, 0xf7, 0x8d, 0xa1, 0x5d, 0xc5, 0x0f, 0xe2, 0x19, 0x64, 0xb5, 0x7d, 0x61, 0xd5, 0x9b,
	0x24, 0xd3, 0x62, 0x36, 0x8e, 0x5e, 0x55, 0xa8, 0x0d, 0xb1, 0x96, 0xcf, 0xf2, 0x29, 0x1e, 0x0a,
	0x33, 0x8e, 0x20, 0xad, 0x17, 0x72, 0x21, 0xd3, 0x69, 0xbd, 0xf8, 0x15, 0x4e, 0x3b, 0xc2, 0x47,
	0xd0, 0x7f, 0xe0, 0x77, 0xb2, 0xd2, 0x9a, 0xeb, 0x08, 0x78, 0x08, 0xbd, 0xb9, 0x21, 0x95, 0x89,
	0x5c, 0x18, 0x67, 0x97, 0x50, 0x84, 0xde, 0xf9, 0x72, 0xc9, 0x9f, 0x76, 0x8b, 0x15, 0xe4, 0x01,
	0x6f, 0xd8, 0xbc, 0x59, 0x1c, 0x75, 0x54, 0x34, 0x6d, 0x4e, 0xc6, 0xff, 0xd8, 0xb7, 0xe5, 0xde,
	0xf3, 0x40, 0x92, 0xf3, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xce, 0x91, 0xbe, 0x5e, 0x53, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserAccountClient is the client API for UserAccount service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserAccountClient interface {
	UserLogin(ctx context.Context, in *UserReq, opts ...grpc.CallOption) (*UserResp, error)
}

type userAccountClient struct {
	cc *grpc.ClientConn
}

func NewUserAccountClient(cc *grpc.ClientConn) UserAccountClient {
	return &userAccountClient{cc}
}

func (c *userAccountClient) UserLogin(ctx context.Context, in *UserReq, opts ...grpc.CallOption) (*UserResp, error) {
	out := new(UserResp)
	err := c.cc.Invoke(ctx, "/proto.UserAccount/UserLogin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserAccountServer is the server API for UserAccount service.
type UserAccountServer interface {
	UserLogin(context.Context, *UserReq) (*UserResp, error)
}

// UnimplementedUserAccountServer can be embedded to have forward compatible implementations.
type UnimplementedUserAccountServer struct {
}

func (*UnimplementedUserAccountServer) UserLogin(ctx context.Context, req *UserReq) (*UserResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserLogin not implemented")
}

func RegisterUserAccountServer(s *grpc.Server, srv UserAccountServer) {
	s.RegisterService(&_UserAccount_serviceDesc, srv)
}

func _UserAccount_UserLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAccountServer).UserLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserAccount/UserLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAccountServer).UserLogin(ctx, req.(*UserReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserAccount_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.UserAccount",
	HandlerType: (*UserAccountServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserLogin",
			Handler:    _UserAccount_UserLogin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hello.proto",
}
